# Generated by Django 4.2 on 2023-04-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_youtube_channel_youtube_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YouTube',
            new_name='Book',
        ),
    ]
