# Generated by Django 4.2 on 2023-04-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_youtube_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
